---
title: "Implementation"
author: "Evan Wu"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
---
```{r Library, warning = FALSE, message = FALSE}
library(tidyverse)
library(ranger)
library(Metrics)

set.seed(840172)
```

```{r Mean Impute Function}

mean_impute <- function(x) {
  mean_value <- mean(x, na.rm = TRUE)
  x[is.na(x)] <- mean_value
  return(x)
}


mean_impute_all_columns <- function(data) {
  for (col in names(data)) {
    if (is.numeric(data[[col]])) {
      mean_value <- mean(data[[col]], na.rm = TRUE)
      data[[col]][is.na(data[[col]])] <- mean_value
    }
  }
  return(data)
}

```


```{r Original Data, warning = FALSE, message = FALSE}
arsenals <- read_csv("Updated Data/arsenal_stats.csv") %>% 
  rename(player_name = `last_name, first_name`) %>% 
  select(player_name, player_id, Season, pitch_type, est_woba, woba, run_value)

xwOBA_si <- arsenals %>% 
  filter(pitch_type == "SIFT") %>% 
  select(player_id, Season, est_woba)

xwOBA_sl <- arsenals %>% 
  filter(pitch_type == "SL") %>% 
  select(player_id, Season, est_woba)

xwOBA_cu <- arsenals %>% 
  filter(pitch_type == "CUKC") %>% 
  select(player_id, Season, est_woba)

xwOBA_ch <- arsenals %>% 
  filter(pitch_type == "CH") %>% 
  select(player_id, Season, est_woba)

xwOBA_fc <- arsenals %>% 
  filter(pitch_type == "FC") %>% 
  select(player_id, Season, est_woba)

xwOBA_ff <- arsenals %>% 
  filter(pitch_type == "FF") %>% 
  select(player_id, Season, est_woba)


si <- read_csv("Updated Data/SI_interpitch_2020-2023.csv") %>% 
  select(-...1:-player_name) %>% 
left_join(xwOBA_si, by = c("mlbAM_ID" = "player_id", "Season" = "Season")) %>% 
  filter(!is.na(est_woba)) %>% 
  mean_impute_all_columns()
  # mutate_all(~ifelse(is.na(.), 100, .))

sl <- read_csv("Updated Data/SL_interpitch_2020-2023.csv") %>% 
  select(-...1:-player_name) %>% 
left_join(xwOBA_sl, by = c("mlbAM_ID" = "player_id", "Season" = "Season")) %>% 
  filter(!is.na(est_woba)) %>% 
  mean_impute_all_columns()
  # mutate_all(~ifelse(is.na(.), 100, .))

cu <- read_csv("Updated Data/CU_interpitch_2020-2023.csv") %>% 
  select(-...1:-player_name) %>% 
left_join(xwOBA_cu, by = c("mlbAM_ID" = "player_id", "Season" = "Season")) %>% 
  filter(!is.na(est_woba)) %>% 
  mean_impute_all_columns()
  # mutate_all(~ifelse(is.na(.), 100, .))

ch <- read_csv("Updated Data/CH_interpitch_2020-2023.csv") %>% 
  select(-...1:-player_name) %>% 
left_join(xwOBA_ch, by = c("mlbAM_ID" = "player_id", "Season" = "Season")) %>% 
  filter(!is.na(est_woba)) %>% 
  mean_impute_all_columns()
  # mutate_all(~ifelse(is.na(.), 100, .))

fc <- read_csv("Updated Data/FC_interpitch_2020-2023-3.csv") %>% 
  select(-...1:-player_name) %>% 
left_join(xwOBA_fc, by = c("mlbAM_ID" = "player_id", "Season" = "Season")) %>% 
  filter(!is.na(est_woba)) %>% 
  mean_impute_all_columns()
  # mutate_all(~ifelse(is.na(.), 100, .))

ff <- read_csv("Updated Data/FF_interpitch_2020-2023.csv") %>% 
  select(-...1:-player_name) %>% 
left_join(xwOBA_ff, by = c("mlbAM_ID" = "player_id", "Season" = "Season")) %>% 
  filter(!is.na(est_woba)) %>% 
  mean_impute_all_columns()
  # mutate_all(~ifelse(is.na(.), 100, .))

```

```{r Test Data, warning = FALSE, message = FALSE}
si_test <- si %>% 
  filter(Season != 2023) %>% 
  filter(Season != 2020) %>% 
  select(-mlbAM_ID, -Season)

sl_test <- sl %>% 
  filter(Season != 2023) %>% 
  filter(Season != 2020) %>%
  select(-mlbAM_ID, -Season)

cu_test <- cu %>% 
  filter(Season != 2023) %>% 
  filter(Season != 2020) %>%
  select(-mlbAM_ID, -Season)

ch_test <- ch %>% 
  filter(Season != 2023) %>% 
  filter(Season != 2020) %>%
  select(-mlbAM_ID, -Season)

fc_test <- fc %>% 
  filter(Season != 2023) %>% 
  filter(Season != 2020) %>%
  select(-mlbAM_ID, -Season)

ff_test <- ff %>% 
  filter(Season != 2023) %>% 
  filter(Season != 2020) %>%
  select(-mlbAM_ID, -Season)
```

```{r 2023 Data, warning = FALSE, message = FALSE}
si_2023 <- si %>% 
  filter(Season == 2023) %>% 
  select(-mlbAM_ID, -Season)

sl_2023 <- sl %>% 
  filter(Season == 2023) %>% 
  select(-mlbAM_ID, -Season)

cu_2023 <- cu %>% 
  filter(Season == 2023) %>% 
  select(-mlbAM_ID, -Season)

ch_2023 <- ch %>% 
  filter(Season == 2023) %>% 
  select(-mlbAM_ID, -Season)

fc_2023 <- fc %>% 
  filter(Season == 2023) %>% 
  select(-mlbAM_ID, -Season)

ff_2023 <- ff %>% 
  filter(Season == 2023) %>% 
  select(-mlbAM_ID, -Season)
```

```{r Sinker Model}
si_model <- ranger(est_woba ~ ., data = si_test)
```

```{r Slider Model}
sl_model <- ranger(est_woba ~ ., data = sl_test)
```

```{r Curveball Model}
cu_model <- ranger(est_woba ~ ., data = cu_test)
```

```{r Change-Up Model}
ch_model <- ranger(est_woba ~ ., data = ch_test)
```

```{r Cutter Model}
fc_model <- ranger(est_woba ~ ., data = fc_test)
```

```{r Fastball Model}
ff_model <- ranger(est_woba ~ ., data = ff_test)
```

```{r Predictions 2023, warning = FALSE, message = FALSE}
# Sinker
SI <- si_2023 %>% 
  mutate(prediction = predict(si_model, si_2023)$predictions) %>% 
  rename(observed = est_woba) %>% 
  select(observed, prediction)

rmse_si <- rmse(SI$observed, SI$prediction)


# Slider
SL <- sl_2023 %>% 
  mutate(prediction = predict(sl_model, sl_2023)$predictions) %>% 
  rename(observed = est_woba) %>% 
  select(observed, prediction)

rmse_sl <- rmse(SL$observed, SL$prediction)


# Curveball
CU <- cu_2023 %>% 
  mutate(prediction = predict(cu_model, cu_2023)$predictions) %>% 
  rename(observed = est_woba) %>% 
  select(observed, prediction)

rmse_cu <- rmse(CU$observed, CU$prediction)


# Change-Up
CH <- ch_2023 %>% 
  mutate(prediction = predict(ch_model, ch_2023)$predictions) %>% 
  rename(observed = est_woba) %>% 
  select(observed, prediction)

rmse_ch <- rmse(CH$observed, CH$prediction)


# Cutter
FC <- fc_2023 %>% 
  mutate(prediction = predict(fc_model, fc_2023)$predictions) %>% 
  rename(observed = est_woba) %>% 
  select(observed, prediction)

rmse_fc <- rmse(FC$observed, FC$prediction)


# Fastball
FF <- ff_2023 %>% 
  mutate(prediction = predict(ff_model, ff_2023)$predictions) %>% 
  rename(observed = est_woba) %>% 
  select(observed, prediction)

rmse_ff <- rmse(FF$observed, FF$prediction)
```

##### RMSEs

Cutter: `r round(rmse_fc, 4)`


Slider: `r round(rmse_sl, 4)`


Fastball: `r round(rmse_ff, 4)`


Sinker: `r round(rmse_si, 4)`


Curveball: `r round(rmse_cu, 4)`


Change-Up: `r round(rmse_ch, 4)`



```{r}
CU %>% 
  ggplot(aes(x = observed, y = prediction)) +
  geom_point() +
  labs(title = "Curveball")


SL %>% 
  ggplot(aes(x = observed, y = prediction)) +
  geom_point() +
  labs(title = "Slider")


SI %>% 
  ggplot(aes(x = observed, y = prediction)) +
  geom_point() +
  labs(title = "Sinker")


CH %>% 
  ggplot(aes(x = observed, y = prediction)) +
  geom_point() +
  labs(title = "Change-Up")


FC %>% 
  ggplot(aes(x = observed, y = prediction)) +
  geom_point() +
  labs(title = "Cutter")


FF %>% 
  ggplot(aes(x = observed, y = prediction)) +
  geom_point() +
  labs(title = "Fastball")
```

