---
title: "EDA"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Data.R")
```


```{r message = FALSE}
library(tidyverse)
library(readxl)
library(patchwork)
library(kableExtra)
library(knitr)
library(ranger)
library(vip)
library(rpart)
library(rpart.plot)
```

```{r Slider, message = FALSE, echo = FALSE}
movement_slider_r <- Data %>% 
  filter(pitch_type == "SL") %>% 
  filter(pitch_hand == "R") %>% 
  ggplot() +
  geom_vline(xintercept = 0, color = "black") +
  geom_hline(yintercept = 0, color = "black") +
  geom_point(aes(x = pitcher_break_x, y = pitcher_break_z,
                 color = `Stuff`), alpha = 0.7) +
  scale_y_reverse() +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "Horizontal Break",
       y = "Vertical Break",
       title = "Sliders (R)") +
  xlim(40, -40) + ylim(60, -60) +
  theme(axis.title = element_blank(), axis.ticks = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect("white"),
        plot.title = element_text(hjust = 0.5)) + 
  coord_fixed(ratio = 1)
  
movement_slider_l <- Data %>% 
    filter(pitch_type == "SL") %>% 
    filter(pitch_hand == "L") %>% 
  ggplot() +
    geom_vline(xintercept = 0, color = "black") +
    geom_hline(yintercept = 0, color = "black") +
    geom_point(aes(x = pitcher_break_x, y = pitcher_break_z,
                   color = `Stuff`), alpha = 0.7) +
    scale_y_reverse() +
    scale_color_gradient(low = "blue", high = "red") +
    labs(x = "Horizontal Break",
         y = "Vertical Break",
         title = "Sliders (L)") +
    xlim(-40, 40) + ylim(60, -60) +
    theme(axis.title = element_blank(), axis.ticks = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_rect("white"),
          plot.title = element_text(hjust = 0.5)) + 
    coord_fixed(ratio = 1)

movement_slider_l + movement_slider_r
rm(movement_slider_l)
rm(movement_slider_r)
```

``` {r Fastball, warning = FALSE, message = FALSE, echo = FALSE}
# 4-Seam Fastball ####
movement_fourseam_r <- Data %>% 
  filter(pitch_type == "FF") %>% 
  filter(pitch_hand == "R") %>% 
  ggplot() +
  geom_vline(xintercept = 0, color = "black") +
  geom_hline(yintercept = 0, color = "black") +
  geom_point(aes(x = pitcher_break_x, y = pitcher_break_z,
                 color = `Stuff`), alpha = 0.7) +
  scale_y_reverse() +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "Horizontal Break",
       y = "Vertical Break",
       title = "4-Seam (R)") +
  xlim(-30, 30) + ylim(30, -30) +
  theme(axis.title = element_blank(), axis.ticks = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect("white"),
        plot.title = element_text(hjust = 0.5)) + 
  coord_fixed(ratio = 1)

movement_fourseam_l <- Data %>% 
  filter(pitch_type == "FF") %>% 
  filter(pitch_hand == "L") %>% 
  ggplot() +
  geom_vline(xintercept = 0, color = "black") +
  geom_hline(yintercept = 0, color = "black") +
  geom_point(aes(x = pitcher_break_x, y = pitcher_break_z,
                 color = `Stuff`), alpha = 0.7) +
  scale_y_reverse() +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "Horizontal Break",
       y = "Vertical Break",
       title = "Four-Seam (L)") +
  xlim(30, -30) + ylim(30, -30) +
  theme(axis.title = element_blank(), axis.ticks = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect("white"),
        plot.title = element_text(hjust = 0.5)) + 
  coord_fixed(ratio = 1)

movement_fourseam_l + movement_fourseam_r

rm(movement_fourseam_l)
rm(movement_fourseam_r)



Data %>% 
  filter(pitch_type == "FF") %>% 
  filter(pitch_hand == "R") %>% 
  filter(avg_speed >= 94) %>% 
  ggplot() +
  geom_vline(xintercept = 0, color = "black") +
  geom_hline(yintercept = 0, color = "black") +
  geom_point(aes(x = pitcher_break_x, y = pitcher_break_z,
                 color = avg_speed), alpha = 0.75) +
  scale_y_reverse() +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "Horizontal Break",
       y = "Vertical Break",
       title = "4-Seam (R)",
       color = "MPH") +
  xlim(-30, 30) + ylim(30, -30) +
  theme(axis.title = element_blank(), axis.ticks = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect("white"),
        plot.title = element_text(hjust = 0.5)) + 
  coord_fixed(ratio = 1)
```

``` {r Pitch Results, message = FALSE, echo = FALSE}
pitches %>% 
  select(result:release_extension) %>% 
  filter(pitches > 9) %>% 
  filter(player_name == "Heaney, Andrew") %>% 
  select(result:pitches, player_name:pitch_percent, woba,
         launch_speed:velocity) %>% 
  filter(pitch_type == "FF") %>% 
  ggplot(aes(x = result, y = woba, fill = pitches)) +
  geom_col() +
  scale_fill_continuous(low = "#FFE338", high = "forestgreen") +
  labs(y = "wOBA",
       x = "Result",
       fill = "# of Pitches",
       title = "Andrew Heaney Batted Balls on 4-Seam Fastballs") +
  theme_classic()


```

```{r, warning = FALSE, message = FALSE, echo = FALSE}
results <- pitches %>% 
  select(-c(pos3_int_start_distance:pos9_int_start_distance))

movement <- Data %>% 
  select(pitch_type, pitch_type_name, Stuff, `Stf+ Pitch`:tail, 
         avg_speed, pitches_thrown, pitch_per, spin_rate, playerID) %>% 
  rename(pitch_prop = pitch_per) %>% 
  filter(!is.na(`Stf+ Pitch`))

league <- movement %>% 
  group_by(pitch_type_name) %>% 
  summarize("horizontal" = 
              weighted.mean(pitcher_break_x, pitches_thrown),
            "vertical" = 
              weighted.mean(pitcher_break_z, pitches_thrown),
            "prop" =  
              weighted.mean(pitch_prop, pitches_thrown),
            "spin" =  
              weighted.mean(spin_rate, pitches_thrown, na.rm = TRUE)) %>% 
  as.data.frame()
  
league %>% 
  kable(digits = 2, align = "c",
        col.names = c("Pitch", "Horizontal", "Vertical",
                      "Pitch Proportion", "Spin Rate")) %>% 
  kable_styling(full_width = T)


movement %>% 
    filter(pitch_type == "SL") %>%
  ggplot() +
    geom_vline(xintercept = 0, color = "white") +
    geom_hline(yintercept = 0, color = "white") +
    geom_point(aes(x = pitcher_break_x-league$horizontal, 
                   y = pitcher_break_z-league$vertical,
                   color = `Stf+ Pitch`), alpha = 0.85) +
    scale_y_reverse() +
    scale_color_gradient(low = "aliceblue", high = "dodgerblue3") +
    labs(x = "Horizontal Break",
         y = "Vertical Break",
         title = "Sliders") +
    xlim(-30, 30) + ylim(30, -30) +
    theme(axis.title = element_blank(), axis.ticks = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_rect("black"),
          plot.title = element_text(hjust = 0.5)) + 
    coord_fixed(ratio = 1)
```

```{r Exploring Stuff+, echo = FALSE}
movement %>% 
  ggplot(aes(x = `Stf+ Pitch`, color = pitch_type)) +
  geom_histogram(fill = "black", binwidth = 2) +
  labs(x = "Stuff+",
       y = "",
       color = "Pitches") +
  theme_classic()


movement %>% 
  filter(pitch_type == "CU") %>% 
  ggplot(aes(x = `Stf+ Pitch`)) +
  geom_histogram(color = "white", fill = "black", binwidth = 2) +
  labs(x = "Stuff+",
       y = "",
       color = "Pitches") +
  theme_classic()
```

```{r Classification Table, echo = FALSE}
Stf_Class <- c("< 55", "< 70", "< 85", "< 95", " < 105", 
                            "< 115", "< 130", "< 145", "< 160", "≥ 160") %>% 
  cbind(1:10) %>% 
  as.data.frame()
names(Stf_Class) <- c("Stf+ Range", "Class")
Stf_Class <- Stf_Class %>% 
  select(Class, `Stf+ Range`)

Stf_Class %>% 
  kable(caption = "Pitch Classifications for Stuff+") %>% 
  kable_styling(full_width = T)
```

``` {r Classifying Stuff+, echo = FALSE, warning = FALSE, message = FALSE}
movement <- movement %>% 
  mutate(pitch_class = 
           case_when(
             `Stf+ Pitch` < 55 ~ 1,
             `Stf+ Pitch` < 70 ~ 2,
             `Stf+ Pitch` < 85 ~ 3,
             `Stf+ Pitch` < 95 ~ 4,
             `Stf+ Pitch` < 105 ~ 5,
             `Stf+ Pitch` < 115 ~ 6,
             `Stf+ Pitch` < 130 ~ 7,
             `Stf+ Pitch` < 145 ~ 8,
             `Stf+ Pitch` < 160 ~ 9,
             `Stf+ Pitch` >= 160 ~ 10,
    )
  )

movement %>% 
  group_by(pitch_class) %>% 
  summarize(Count = n()) %>% 
  as.data.frame() %>% 
  ggplot(aes(x = pitch_class, y = Count)) + 
  geom_col(color = "black", fill = "forestgreen") +
  geom_label(aes(label = Count), vjust = -0.5,
             color = "forestgreen", fill = "lightgrey") +
  scale_x_continuous(breaks = seq(1, 10, 1)) +
  scale_y_continuous(breaks = seq(0, 600, 100), limits = c(0, 600)) +
  theme_classic() +
  NULL


movement %>% 
    filter(pitch_type == "SL",
           pitch_class > 2) %>%
  ggplot() +
    geom_vline(xintercept = 0, color = "white") +
    geom_hline(yintercept = 0, color = "white") +
    geom_point(aes(x = pitcher_break_x-league$horizontal, 
                   y = pitcher_break_z-league$vertical,
                   color = as.factor(pitch_class)), alpha = 0.85) +
    scale_y_reverse() +
    labs(x = "Horizontal Break",
         y = "Vertical Break",
         title = "Sliders",
         color = "Pitch Class") +
    xlim(-30, 30) + ylim(30, -30) +
    theme(axis.title = element_blank(), axis.ticks = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_rect("black"),
          plot.title = element_text(hjust = 0.5)) + 
    coord_fixed(ratio = 1)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
pitches <- pitches %>%
  mutate(Type = 
           case_when(
             pitch_type == "CH" ~ "off_speed",
             pitch_type == "FS" ~ "off_speed",
             pitch_type == "SL" ~ "breaking_ball",
             pitch_type == "CU" ~ "breaking_ball",
             pitch_type == "FF" ~ "fastball",
             pitch_type == "FC" ~ "fastball",
             pitch_type == "SI" ~ "fastball"
           )) 
pitches %>%   
  ggplot(aes(x = launch_speed, y = launch_angle, 
             color = result)) +
  geom_point(alpha = 0.7) +
  theme_classic() +
  labs(y = "Launch Angle", x = "Exit Velocity")


movement %>% 
  filter(`Stf+ Pitch` >= 130,
           Stuff > 110,
           pitch_type == "SL" | pitch_type == "CU") %>%
  ggplot() +
    geom_vline(xintercept = 0, color = "white") +
    geom_hline(yintercept = 0, color = "white") +
    geom_point(aes(x = pitcher_break_x-league$horizontal, 
                   y = pitcher_break_z-league$vertical,
                   color = pitch_type), alpha = 0.85) +
    scale_y_reverse() +
    labs(x = "Horizontal Break",
         y = "Vertical Break",
         title = "Above Average Breaking Balls for Above Average Pitchers",
         color = "Pitch") +
    xlim(-20, 20) + ylim(40, -40) +
    theme(axis.title = element_blank(), axis.ticks = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_rect("black"),
          plot.title = element_text(hjust = 0.5)) + 
    coord_fixed(ratio = 1)


movement %>% 
  filter(`Stf+ Pitch` >= 130,
           Stuff > 110,
           pitch_type == "FS" | pitch_type == "CH") %>%
  ggplot() +
    geom_vline(xintercept = 0, color = "white") +
    geom_hline(yintercept = 0, color = "white") +
    geom_point(aes(x = pitcher_break_x-league$horizontal, 
                   y = pitcher_break_z-league$vertical,
                   color = pitch_type), alpha = 0.85) +
    scale_y_reverse() +
    labs(x = "Horizontal Break",
         y = "Vertical Break",
         title = "Above Average Off-Speed Pitches for Above Average Pitchers",
         color = "Pitch") +
    xlim(-20, 20) + ylim(20, -20) +
    theme(axis.title = element_blank(), axis.ticks = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_rect("black"),
          plot.title = element_text(hjust = 0.5)) + 
    coord_fixed(ratio = 1)


movement %>% 
  filter(`Stf+ Pitch` >= 130,
           Stuff > 110,
           pitch_type == "FF" | pitch_type == "FC" | pitch_type == "SI") %>%
  ggplot() +
    geom_vline(xintercept = 0, color = "white") +
    geom_hline(yintercept = 0, color = "white") +
    geom_point(aes(x = pitcher_break_x-league$horizontal, 
                   y = pitcher_break_z-league$vertical,
                   color = pitch_type), alpha = 0.85) +
    scale_y_reverse() +
    labs(x = "Horizontal Break",
         y = "Vertical Break",
         title = "Above Average Fastballs for Above Average Pitchers",
         color = "Pitch") +
    xlim(-20, 20) + ylim(30, -30) +
    theme(axis.title = element_blank(), axis.ticks = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_rect("black"),
          plot.title = element_text(hjust = 0.5)) + 
    coord_fixed(ratio = 1)
```

```{r Speed Differential, echo = FALSE, warning = FALSE, message = FALSE}
Data2 %>% 
  filter(speed_diff < 0) %>% 
  ggplot(aes(x = speed_diff, y = `Stf+ Pitch`)) +
  theme(panel.background = element_rect("black"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line("darkgray")) +
  geom_hline(yintercept = 100, color = "green", size = 1.25, alpha = 0.3) +
  geom_point(shape = 18, size = 2, alpha = 0.8, aes(color = avg_speed)) +
  geom_smooth(se = FALSE, color = "gray92", size = 1.5) +
  labs(x = "Speed Differential (vs. Fastball)",
       y = "Pitch Stuff+",
       color = "Pitch Speed") +
  scale_color_gradient(low = "yellow", high = "red", limits = c(70, 100)) +
  scale_x_reverse() +
  NULL



Data2 %>% 
  filter(speed_diff < 0) %>% 
  ggplot(aes(x = speed_diff, y = `Stf+ Pitch`)) +
  theme(panel.background = element_rect("black"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line("darkgray")) +
  geom_hline(yintercept = 100, color = "yellow", size = 1, alpha = 0.5) +
  geom_point(shape = 18, size = 2, alpha = 0.8, aes(color = pitch_type_name)) +
  geom_smooth(se = FALSE, color = "gray92", size = 1.5) +
  labs(x = "Speed Differential (vs. Fastball)",
       y = "Pitch Stuff+",
       color = "Pitch") +
  scale_x_reverse() +
  NULL
```

```{r Pitch Prop, echo = FALSE, warning = FALSE, message = FALSE}
Data2 %>% 
  ggplot(aes(x = avg_speed, y = `Stf+ Pitch`,
             color = pitch_per)) +
  theme(panel.background = element_rect("black"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line("darkgray")) +
  geom_hline(yintercept = 100, color = "yellow", size = 1, alpha = 0.5) +
  geom_point(alpha = 0.8) +
  geom_smooth(se = FALSE, color = "gray92", size = 1.5) +
  labs(x = "Pitch Speed",
       y = "Pitch Stuff+",
       color = "Pitch Proportion") +
  scale_color_gradient(low = "yellow", high = "red", limits = c(0,1)) +
  NULL


Data2 %>% 
  ggplot(aes(x = (pitch_per-league$prop)/league$prop, y = `Stf+ Pitch`,
             color = woba)) +
  theme(panel.background = element_rect("black"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line("darkgray")) +
  geom_hline(yintercept = 100, color = "yellow", size = 1, alpha = 0.7) +
  geom_vline(xintercept = 0, color = "yellow", size = 1, alpha = 0.7) +
  geom_point(alpha = 0.8) +
  geom_smooth(se = FALSE, color = "gray92", size = 1.5) +
  labs(x = "Pitch Usage (vs. League Average)",
       y = "Pitch Stuff+",
       color = "wOBA") +
  scale_color_gradient(low = "green", high = "red") +
  scale_x_continuous(limits = c(-1,2.5), labels = scales::percent) +
  NULL


Data2 %>% 
  ggplot(aes(x = pitch_per-league$prop, y = `Stf+ Pitch`,
             color = woba)) +
  theme(panel.background = element_rect("black"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line("darkgray")) +
  geom_hline(yintercept = 100, color = "yellow", size = 1, alpha = 0.7) +
  geom_vline(xintercept = 0, color = "yellow", size = 1, alpha = 0.7) +
  geom_point(alpha = 0.8) +
  geom_smooth(se = FALSE, color = "gray92", size = 1.5) +
  labs(x = "Pitch Usage",
       y = "Pitch Stuff+",
       color = "wOBA") +
  scale_color_gradient(low = "green", high = "red") +
  scale_x_continuous(limits = c(-0.5, 0.75), labels = scales::percent) +
  NULL
```

```{r Tree Model}
base <- Data2 %>% 
  select(Name, year, pitch_hand:Stuff, `Stf+ Pitch`, pitcher_break_z,
         pitcher_break_x, avg_speed, spin_rate, pitches_thrown, pitch_per,
         run_value:hard_hit_percent, fb_type:speed_diff)


tree_input <- base %>% 
  filter(!is.na(`Stf+ Pitch`), !is.na(run_value), !is.na(spin_rate),
         !is.na(fb_stuff), !is.na(fb_speed), !is.na(fb_thrown),
         !is.na(speed_diff)) %>% 
  select(-Name:-pitch_type_name, -fb_type) %>% 
  rename(pitch_stuff = `Stf+ Pitch`) %>% 
  select(-est_woba, -slg, -ba, -run_value_per_100, -run_value, -est_slg,
         -est_ba)

mlb_rf <- ranger(woba ~ ., data = tree_input, num.trees = 1000,
                      importance = "impurity") 

mlb_rf

vip(mlb_rf, geom = "point") + theme_bw()
```

```{r Tree of Component Variables, echo = FALSE}
set.seed(13*38*51)

# Lots of Variables
model_data_full <- tree_input %>% 
  select(woba, pitch_stuff, pitcher_break_z, pitcher_break_x, avg_speed, spin_rate,
         pitch_per, fb_stuff, fb_thrown, speed_diff) %>% 
  filter(speed_diff != 0)

model_full <- ranger(woba ~ ., data = model_data_full, num.trees = 1000,
                      importance = "impurity") 

vip(model_full, geom = "point") + 
  labs(title = "Thorough Model",
       caption = "Variables: pitch_stuff, pitcher_break_z, pitcher_break_x, 
       avg_speed, spin_rate, pitch_per, fb_stuff,
       fb_thrown, speed_diff") +
  theme_bw()


model_data_full %>% 
  lm(woba ~ pitch_stuff + pitcher_break_z + pitcher_break_x + avg_speed + 
       spin_rate + pitch_per + fb_stuff + fb_thrown + speed_diff,
     data = .) %>% 
  summary()


tree_1 <- rpart(formula =woba ~ pitch_stuff + pitcher_break_z + pitcher_break_x + 
                  avg_speed + spin_rate + pitch_per + fb_stuff + fb_thrown + 
                  speed_diff,
     data = model_data_full, method = "anova")

tree_1 %>% rpart.plot()


# Fewer Variables
model_data_reduced <- tree_input %>% 
  select(woba, pitcher_break_z, pitcher_break_x, avg_speed, spin_rate, 
         speed_diff) %>% 
  filter(speed_diff != 0) %>% 
  select(-speed_diff)

model_reduced <- ranger(woba ~ ., data = model_data_reduced, num.trees = 1000,
                      importance = "impurity") 

vip(model_reduced, geom = "point") + 
  labs(title = "Reduced Model",
       caption = "Variables: pitcher_break_z, pitcher_break_x, avg_speed, spin_rate") +
  theme_bw()

model_data_reduced %>% 
  lm(woba ~ pitcher_break_z + pitcher_break_x +avg_speed + spin_rate, data = .) %>% 
  summary()


tree_2 <- rpart(formula = woba ~ pitcher_break_z + pitcher_break_x + 
                  avg_speed + spin_rate,
     data = model_data_reduced, method = "anova")

tree_2 %>% rpart.plot()


# Fewer Variables, non-comparable population
model_data_reduced <- tree_input %>% 
  select(woba, pitcher_break_z, pitcher_break_x, avg_speed, spin_rate)

model_reduced <- ranger(woba ~ ., data = model_data_reduced, num.trees = 1000,
                      importance = "impurity") 

vip(model_reduced, geom = "point") + 
   labs(title = "Reduced Model",
        subtitle = "Primary Fastball Included",
       caption = "Variables: pitcher_break_z, pitcher_break_x, avg_speed, spin_rate") +
  theme_bw()

```

