---
title: "Ethan"
author: "Ethan Park"
date: "2023-07-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(mgcv)
library(tidymodels)
library(ggplot2)
```

```{r}
statcast = read.csv('./Ethan-Data/Statcast/statcast_2020-2022.csv')
pitch_types = c('FF', 'FC', 'CH', 'CU', 'SL', 'SI')

remove_outliers <- function(df, col_names) {
  for (col_name in col_names) {
    Q1 <- quantile(df[[col_name]], 0.25)
    Q3 <- quantile(df[[col_name]], 0.75)
    
    IQR <- Q3 - Q1
    
    lower_bound <- Q1 - 1.5 * IQR
    upper_bound <- Q3 + 1.5 * IQR
    
    df <- df[df[[col_name]] >= lower_bound & df[[col_name]] <= upper_bound, ]
  }
  return(df)
}

inters = list()
for (pitch_type in pitch_types) {
  file_path = sprintf('./Ethan-Data/Inter-Pitch/%s_interpitch_2020-2022.csv', pitch_type)
  df <- read.csv(file_path)
  
  df <- remove_outliers(df, col_names = c('est_woba', 'Stuff'))
  inters[[pitch_type]] <- df
}
```

```{r}
rmse <- function(observed, predicted){
  n <- length(observed)
  sqrt(sum((observed - predicted)^2) / n)}
```

```{r}
cv <- function(pitch, fold){
  prepare <- function(data) {
    folds = data %>% 
      select(mlbAM_ID) %>% 
      distinct(mlbAM_ID) %>% 
      rowwise() %>%
      mutate(group = sample(seq(1, 5, 1), 1))
    
    gam_data <- data %>% 
      left_join(folds, by = 'mlbAM_ID')
    
    return(gam_data)
  }
  
  gam_data <- prepare(inters[[pitch]])
  
  train <- gam_data %>% filter(group != fold)
  gam <- gam(est_woba ~ s(Stuff), data = train, family = gaussian, method = "REML")
  test <- gam_data %>% filter(group == fold)
  
  y_pred <- test %>% mutate(prediction = predict(gam, test)) %>% 
    filter(!is.na(prediction))
  
  gam_pred_df = data.frame(observed = test$est_woba, prediction = y_pred$prediction)
  return(gam_pred_df)
}
```

```{r}
FF_preds = data.frame()
FF_preds <- rbind(cv("FF", "1"),
                  cv("FF", "2"),
                  cv("FF", "3"),
                  cv("FF", "4"),
                  cv("FF", "5"))

FF_rmses <- round(rmse(FF_preds$observed, FF_preds$prediction), 4)

print(FF_preds %>%
  ggplot(aes(x = observed, y = prediction)) +
  geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) +
  geom_smooth(se = FALSE, method = lm) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  scale_x_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  labs(x = "Observed",
       y = "Predicted",
       title = paste("FF xwOBA GAM Predictions"),
       caption = paste("RMSE:",
                       round(rmse(FF_preds$observed, FF_preds$prediction), 4))) +
  theme_dark() +
  theme(plot.title = element_text(hjust = 0.5)))
```

```{r}
FC_preds = data.frame()
FC_preds <- rbind(cv("FC", "1"),
                  cv("FC", "2"),
                  cv("FC", "3"),
                  cv("FC", "4"),
                  cv("FC", "5"))

FC_rmses <- round(rmse(FC_preds$observed, FC_preds$prediction), 4)

print(FC_preds %>%
  ggplot(aes(x = observed, y = prediction)) +
  geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) +
  geom_smooth(se = FALSE, method = lm) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  scale_x_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  labs(x = "Observed",
       y = "Predicted",
       title = paste("FC xwOBA GAM Predictions"),
       caption = paste("RMSE:",
                       round(rmse(FC_preds$observed, FC_preds$prediction), 4))) +
  theme_dark() +
  theme(plot.title = element_text(hjust = 0.5)))
```

```{r}
CH_preds = data.frame()
CH_preds <- rbind(cv("CH", "1"),
                  cv("CH", "2"),
                  cv("CH", "3"),
                  cv("CH", "4"),
                  cv("CH", "5"))

CH_rmses <- round(rmse(CH_preds$observed, CH_preds$prediction), 4)

print(CH_preds %>%
  ggplot(aes(x = observed, y = prediction)) +
  geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) +
  geom_smooth(se = FALSE, method = lm) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  scale_x_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  labs(x = "Observed",
       y = "Predicted",
       title = paste("CH xwOBA GAM Predictions"),
       caption = paste("RMSE:",
                       round(rmse(CH_preds$observed, CH_preds$prediction), 4))) +
  theme_dark() +
  theme(plot.title = element_text(hjust = 0.5)))
```

```{r}
CU_preds = data.frame()
CU_preds <- rbind(cv("CU", "1"),
                  cv("CU", "2"),
                  cv("CU", "3"),
                  cv("CU", "4"),
                  cv("CU", "5"))

CU_rmses <- round(rmse(CU_preds$observed, CU_preds$prediction), 4)

print(CU_preds %>%
  ggplot(aes(x = observed, y = prediction)) +
  geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) +
  geom_smooth(se = FALSE, method = lm) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  scale_x_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  labs(x = "Observed",
       y = "Predicted",
       title = paste("CU xwOBA GAM Predictions"),
       caption = paste("RMSE:",
                       round(rmse(CU_preds$observed, CU_preds$prediction), 4))) +
  theme_dark() +
  theme(plot.title = element_text(hjust = 0.5)))
```

```{r}
SL_preds = data.frame()
SL_preds <- rbind(cv("SL", "1"),
                  cv("SL", "2"),
                  cv("SL", "3"),
                  cv("SL", "4"),
                  cv("SL", "5"))

SL_rmses <- round(rmse(SL_preds$observed, SL_preds$prediction), 4)

print(SL_preds %>%
  ggplot(aes(x = observed, y = prediction)) +
  geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) +
  geom_smooth(se = FALSE, method = lm) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  scale_x_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  labs(x = "Observed",
       y = "Predicted",
       title = paste("SL xwOBA GAM Predictions"),
       caption = paste("RMSE:",
                       round(rmse(SL_preds$observed, SL_preds$prediction), 4))) +
  theme_dark() +
  theme(plot.title = element_text(hjust = 0.5)))
```

```{r}
SI_preds = data.frame()
SI_preds <- rbind(cv("SI", "1"),
                  cv("SI", "2"),
                  cv("SI", "3"),
                  cv("SI", "4"),
                  cv("SI", "5"))

SI_rmses <- round(rmse(SI_preds$observed, SI_preds$prediction), 4)

print(SI_preds %>%
  ggplot(aes(x = observed, y = prediction)) +
  geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) +
  geom_smooth(se = FALSE, method = lm) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  scale_x_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  labs(x = "Observed",
       y = "Predicted",
       title = paste("SI xwOBA GAM Predictions"),
       caption = paste("RMSE:",
                       round(rmse(SI_preds$observed, SI_preds$prediction), 4))) +
  theme_dark() +
  theme(plot.title = element_text(hjust = 0.5)))
```






```{r}
statcast = read.csv('./Ethan-Data/Statcast/statcast_2020-2022.csv')
pitch_types = c('FF', 'FC', 'CH', 'CU', 'SL', 'SI')

mean_impute <- function(x) {
  mean_value <- mean(x, na.rm = TRUE)
  x[is.na(x)] <- mean_value
  return(x)
}

remove_outliers <- function(df, col_names) {
  for (col_name in col_names) {
    Q1 <- quantile(df[[col_name]], 0.25)
    Q3 <- quantile(df[[col_name]], 0.75)
    
    IQR <- Q3 - Q1
    
    lower_bound <- Q1 - 1.5 * IQR
    upper_bound <- Q3 + 1.5 * IQR
    
    df <- df[df[[col_name]] >= lower_bound & df[[col_name]] <= upper_bound, ]
  }
  return(df)
}

inters = list()
for (pitch_type in pitch_types) {
  file_path = sprintf('./Ethan-Data/Inter-Pitch/%s_interpitch_2020-2022.csv', pitch_type)
  df <- read.csv(file_path)
  
  df <- remove_outliers(df, col_names = c('est_woba', 'Stuff'))
  df <- as.data.frame(lapply(df, mean_impute))
  
  inters[[pitch_type]] <- df
}
```


```{r}
cv_inter <- function(pitch, fold){
  prepare <- function(data) {
    folds = data %>% 
      select(mlbAM_ID) %>% 
      distinct(mlbAM_ID) %>% 
      rowwise() %>%
      mutate(group = sample(seq(1, 5, 1), 1))
    
    gam_data <- data %>% 
      left_join(folds, by = 'mlbAM_ID')
    
    return(gam_data)
  }
  
  gam_data <- prepare(inters[[pitch]])
  
  train <- gam_data %>% filter(group != fold)
  
  exclude_columns <- c("mlbAM_ID", "Year", "player_name", "pitch_usage", "run_value_per_100", "index")
  exclude_columns <- c(exclude_columns, names(train)[grep("spin_rate", names(train))])
  exclude_columns <- c(exclude_columns, names(train)[grep("FF", names(train))])
  selected_data <- train[, !(names(train) %in% exclude_columns)]
  remaining_columns <- setdiff(names(selected_data), c("est_woba"))
  rhs <- paste('s(', remaining_columns, ', k = 4)', sep = '', collapse = ' + ')
  fml <- paste('est_woba ~', rhs, collapse = ' ')

  gam <- gam(as.formula(fml), data = train, family = gaussian, method = "REML")
  
  # gam <- gam(est_woba ~ s(Stuff) + s)
  test <- gam_data %>% filter(group == fold)
  y_pred <- test %>% mutate(prediction = predict(gam, test)) %>% 
    filter(!is.na(prediction))
  
  gam_pred_df = data.frame(observed = test$est_woba, prediction = y_pred$prediction)
  return(gam_pred_df)
}
```

```{r}
FF_preds_inter = data.frame()
FF_preds_inter <- rbind(cv_inter("FF", "1"),
                  cv_inter("FF", "2"),
                  cv_inter("FF", "3"),
                  cv_inter("FF", "4"),
                  cv_inter("FF", "5"))

FF_rmses_inter <- round(rmse(FF_preds_inter$observed, FF_preds_inter$prediction), 4)

print(FF_preds_inter %>%
  ggplot(aes(x = prediction, y = observed)) +
  geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) +
  geom_smooth(se = FALSE, method = lm) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  scale_x_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  labs(x = "Predicted",
       y = "Observed",
       title = paste("FF Inter-Pitch xwOBA GAM Predictions"),
       caption = paste("RMSE:",
                       round(rmse(FF_preds_inter$observed, FF_preds_inter$prediction), 4))) +
  theme_dark() +
  theme(plot.title = element_text(hjust = 0.5)))
```


```{r}
SL_preds_inter = data.frame()
SL_preds_inter <- rbind(cv_inter("SL", "1"),
                  cv_inter("SL", "2"),
                  cv_inter("SL", "3"),
                  cv_inter("SL", "4"),
                  cv_inter("SL", "5"))

SL_rmses_inter <- round(rmse(SL_preds_inter$observed, SL_preds_inter$prediction), 4)

print(SL_preds_inter %>%
  ggplot(aes(x = observed, y = prediction)) +
  geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) +
  geom_smooth(se = FALSE, method = lm) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  scale_x_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  labs(x = "Observed",
       y = "Predicted",
       title = paste("SL Inter-Pitch xwOBA GAM Predictions"),
       caption = paste("RMSE:",
                       round(rmse(SL_preds_inter$observed, SL_preds_inter$prediction), 4))) +
  theme_dark() +
  theme(plot.title = element_text(hjust = 0.5)))
```

```{r}
SI_preds_inter = data.frame()
SI_preds_inter <- rbind(cv_inter("SI", "1"),
                  cv_inter("SI", "2"),
                  cv_inter("SI", "3"),
                  cv_inter("SI", "4"),
                  cv_inter("SI", "5"))

SI_rmses_inter <- round(rmse(SI_preds_inter$observed, SI_preds_inter$prediction), 4)

print(SI_preds_inter %>%
  ggplot(aes(x = observed, y = prediction)) +
  geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) +
  geom_smooth(se = FALSE, method = lm) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  scale_x_continuous(labels = scales::comma_format(accuracy = 0.001),
                     expand = expansion(mult = c(0, 0.05))) +
  labs(x = "Observed",
       y = "Predicted",
       title = paste("SI Inter-Pitch xwOBA GAM Predictions"),
       caption = paste("RMSE:",
                       round(rmse(SI_preds_inter$observed, SI_preds_inter$prediction), 4))) +
  theme_dark() +
  theme(plot.title = element_text(hjust = 0.5)))
```











<!-- ```{r} -->
<!-- for (pitch_type in names(inters)) { -->
<!--   set.seed(2004) -->

<!--   split <- inters[[pitch_type]] %>% -->
<!--     distinct(mlbAM_ID) %>%  -->
<!--     slice_sample(prop = 0.7) -->

<!--   training <- inters[[pitch_type]] %>%  -->
<!--       filter(mlbAM_ID %in% split$mlbAM_ID) -->

<!--   testing <- inters[[pitch_type]] %>%  -->
<!--     filter(!mlbAM_ID %in% split$mlbAM_ID) -->


<!--   stfplus_pitch_gam <- gam(est_woba ~ s(Stuff),  -->
<!--                  data = training,  -->
<!--                  family = gaussian, method = "REML") -->

<!--   stuff_predictions <- predict(stfplus_pitch_gam, newdata = testing, type = "response") -->
<!--   stuff_gam_pred <- data.frame(observed = testing$est_woba, prediction = stuff_predictions) -->

<!--   print(draw(stfplus_pitch_gam, residuals = TRUE) & ggtitle(pitch_type)  -->
<!--         & xlab("Stuff+")  -->
<!--         & ylab("xwOBA Partial Effect")) -->

  <!-- print(stuff_gam_pred %>% -->
  <!--   ggplot(aes(x = observed, y = prediction)) + -->
  <!--   geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) + -->
  <!--   geom_smooth(se = FALSE, method = lm) + -->
  <!--   scale_y_continuous(labels = scales::comma_format(accuracy = 0.001), -->
  <!--                      expand = expansion(mult = c(0, 0.05))) + -->
  <!--   scale_x_continuous(labels = scales::comma_format(accuracy = 0.001), -->
  <!--                      expand = expansion(mult = c(0, 0.05))) + -->
  <!--   labs(x = "Observed", -->
  <!--        y = "Predicted", -->
  <!--        title = paste(pitch_type, " xwOBA GAM Predictions"), -->
  <!--        caption = paste("RMSE:", -->
  <!--                        round(rmse(stuff_gam_pred$observed, stuff_gam_pred$prediction), 4))) + -->
  <!--   theme_dark() + -->
  <!--   theme(plot.title = element_text(hjust = 0.5))) -->
<!-- } -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # for (pitch_type in names(inters)) { -->
<!-- #   set.seed(2004) -->
<!-- #    -->
<!-- #   split <- inters[[pitch_type]] %>% -->
<!-- #     distinct(mlbAM_ID) %>%  -->
<!-- #     slice_sample(prop = 0.7) -->
<!-- #  -->
<!-- #   training <- inters[[pitch_type]] %>%  -->
<!-- #       filter(mlbAM_ID %in% split$mlbAM_ID) -->
<!-- #      -->
<!-- #   testing <- inters[[pitch_type]] %>%  -->
<!-- #     filter(!mlbAM_ID %in% split$mlbAM_ID) -->
<!-- #    -->
<!-- #   selected_data <- training[, !(names(training) %in% c("mlbAM_ID", "Year", "player_name", -->
<!-- #                                                      "pitch_usage", "run_value_per_100", "index"))] -->
<!-- #   remaining_columns <- setdiff(names(selected_data), c("est_woba")) -->
<!-- #   rhs <- paste('s(', remaining_columns, ')', sep = '', collapse = ' + ') -->
<!-- #   fml <- paste('est_woba ~', rhs, collapse = ' ') -->
<!-- #   big_gam <- gam(as.formula(fml), data = selected_data, family = gaussian, method = "REML") -->
<!-- #    -->
<!-- #   big_predictions <- predict(big_gam, newdata = testing, type = "response") -->
<!-- #   big_gam_pred <- data.frame(observed = testing$est_woba, prediction = big_predictions) -->
<!-- #    -->
<!-- #   print(draw(big_gam, residuals = TRUE) & ggtitle(pitch_type)  -->
<!-- #         & xlab("Stuff+")  -->
<!-- #         & ylab("xwOBA Partial Effect")) -->
<!-- #    -->
<!-- #   print(big_gam_pred %>%  -->
<!-- #     ggplot(aes(x = observed, y = prediction)) + -->
<!-- #     geom_point(color = "#FDB827", shape = 18, size = 2.5, alpha = 0.8) + -->
<!-- #     geom_smooth(se = FALSE, method = lm) + -->
<!-- #     scale_y_continuous(labels = scales::comma_format(accuracy = 0.001), -->
<!-- #                        expand = expansion(mult = c(0, 0.05))) + -->
<!-- #     scale_x_continuous(labels = scales::comma_format(accuracy = 0.001), -->
<!-- #                        expand = expansion(mult = c(0, 0.05))) + -->
<!-- #     labs(x = "Observed", -->
<!-- #          y = "Predicted", -->
<!-- #          title = paste(pitch_type, " xwOBA GAM Predictions"), -->
<!-- #          caption = paste("RMSE:", -->
<!-- #                          round(rmse(big_gam_pred$observed, big_gam_pred$prediction), 4))) + -->
<!-- #     theme_dark() + -->
<!-- #     theme(plot.title = element_text(hjust = 0.5))) -->
<!-- # } -->
<!-- ``` -->
